
export const COMMON_SYMPTOMS = [
  'Abdominal Pain',
  'Diarrhea',
  'Rectal Bleeding',
  'Weight Loss',
  'Fatigue',
  'Fever',
  'Nausea',
  'Vomiting',
  'Joint Pain',
  'Skin Problems',
  'Eye Inflammation',
  'Mouth Ulcers',
  'Perianal Disease',
  'Bowel Obstruction',
  'Malnutrition',
  'Anemia',
  'Depression',
  'Anxiety',
  'Sleep Problems',
  'Loss of Appetite',
]

export const COMMON_MEDICATIONS = [
  'Mesalamine',
  'Sulfasalazine',
  'Metronidazole',
  'Ciprofloxacin',
  'Prednisone',
  'Budesonide',
  'Azathioprine',
  'Mercaptopurine',
  'Methotrexate',
  'Infliximab',
  'Adalimumab',
  'Certolizumab',
  'Vedolizumab',
  'Ustekinumab',
  'Tofacitinib',
  'Probiotics',
  'Iron Supplements',
  'Vitamin B12',
  'Vitamin D',
  'Calcium',
]
